-----BEGIN PRIVATE KEY-----
MIGTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAgEAMBXX
MGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgovj3br2TkMFcqiw3
Ob9SerXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END PRIVATE KEY-----